spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # lowercase thing not working properly, check later.
          # lower-case-service-id: true

server:
  port: 8765
